#!/usr/bin/env bash
# Auto-generate wiki/index.md from cards/ and projects/
# Usage: bash wiki/scripts/gen-index.sh > wiki/index.md
set -euo pipefail

WIKI_DIR="$(cd "$(dirname "$0")/.." && pwd)"

cat <<'HEADER'
# 📒 Wiki Index

> Auto-generated by `scripts/gen-index.sh`. Do not edit manually.

HEADER

# --- Cards ---
echo "## 🃏 Concept Cards ($(ls "$WIKI_DIR/cards/"*.md 2>/dev/null | wc -l))"
echo ""

# Group cards alphabetically with letter headers
current_letter=""
for f in "$WIKI_DIR/cards/"*.md; do
  [ -f "$f" ] || continue
  slug="$(basename "$f" .md)"
  # Extract title from frontmatter
  title="$(sed -n '/^---$/,/^---$/{ /^title:/{ s/^title: *//; s/^["'"'"']//; s/["'"'"']$//; p; q; } }' "$f")"
  [ -z "$title" ] && title="$slug"
  
  first="${slug:0:1}"
  first_upper="$(echo "$first" | tr '[:lower:]' '[:upper:]')"
  if [ "$first_upper" != "$current_letter" ]; then
    current_letter="$first_upper"
    echo "### $current_letter"
    echo ""
  fi
  echo "- [$title](cards/$slug.md)"
done
echo ""

# --- Projects ---
echo "## 📁 Project Notes ($(ls "$WIKI_DIR/projects/"*.md 2>/dev/null | wc -l))"
echo ""

current_letter=""
for f in "$WIKI_DIR/projects/"*.md; do
  [ -f "$f" ] || continue
  slug="$(basename "$f" .md)"
  # Extract title: try frontmatter, then H1, then slug
  title="$(sed -n '/^---$/,/^---$/{ /^title:/{ s/^title: *//; s/^["'"'"']//; s/["'"'"']$//; p; q; } }' "$f")"
  if [ -z "$title" ]; then
    title="$(sed -n '/^# /{ s/^# *//; p; q; }' "$f")"
  fi
  [ -z "$title" ] && title="$slug"
  
  first="${slug:0:1}"
  first_upper="$(echo "$first" | tr '[:lower:]' '[:upper:]')"
  if [ "$first_upper" != "$current_letter" ]; then
    current_letter="$first_upper"
    echo "### $current_letter"
    echo ""
  fi
  echo "- [$title](projects/$slug.md)"
done
echo ""

# --- Stats ---
cards_count=$(ls "$WIKI_DIR/cards/"*.md 2>/dev/null | wc -l)
projects_count=$(ls "$WIKI_DIR/projects/"*.md 2>/dev/null | wc -l)
echo "---"
echo ""
echo "*${cards_count} cards, ${projects_count} project notes. Last generated: $(date -u '+%Y-%m-%d %H:%M UTC').*"
